#!/bin/zsh

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

if ! command_exists brew; then
    echo "Homebrew is not installed. Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    echo "Homebrew check complete"
fi

if ! command_exists ffmpeg; then
    echo "ffmpeg is not installed. Installing ffmpeg..."
    brew install ffmpeg
else
    echo "ffmpeg check complete"
fi

if ! command_exists convert; then
    echo "imageMagick is not installed. Installing ImageMagick..."
    brew install imagemagick
else
    echo "ImageMagick check complete"
fi

if [ "$#" -lt 1 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 /path/to/file.mp4 [fps] [width]"
    exit 1
fi

FILE_PATH="$1"
FPS="${2:-5}"  # Default to 5 fps if not provided
WIDTH="${3:-300}"  # Default to 300 width if not provided
DIRECTORY=$(dirname "$FILE_PATH")
FILE_NAME=$(basename "$FILE_PATH")
FILE_EXTENSION="${FILE_NAME##*.}"
FILE_NAME="${FILE_NAME%.*}"

if [[ "$FILE_EXTENSION" != "mp4" && "$FILE_EXTENSION" != "mov" ]]; then
    echo "Invalid file type. Please provide a .mp4 or .mov file."
    exit 1
fi

if ! [[ "$FPS" =~ ^[0-9]+$ ]] || (( FPS <= 0 )); then
    echo "Invalid fps value. Please provide a positive integer."
    exit 1
fi

if ! [[ "$WIDTH" =~ ^[0-9]+$ ]] || (( WIDTH <= 0 )); then
    echo "Invalid width value. Please provide a positive integer."
    exit 1
fi

SCALE_STR="scale=${WIDTH}:-1:flags=lanczos"

echo "Converting $FILE_EXTENSION file to frames..."
ffmpeg -i "$FILE_PATH" -vf "fps=$FPS,$SCALE_STR" "$DIRECTORY/frame_%04d.png"

echo "Converting frames to GIF..."
convert -delay $((100 / $FPS)) -loop 0 "$DIRECTORY/frame_*.png" "$DIRECTORY/${FILE_NAME}.gif"

delay 1000
if ls "$DIRECTORY"/frame_*.png 1> /dev/null 2>&1; then
    echo "Cleaning up intermediate frames..."
    rm "$DIRECTORY"/frame_*.png
else
    echo "No intermediate frames to clean up."
fi

echo "Conversion complete. GIF saved as $DIRECTORY/${FILE_NAME}.gif"
